### PR TITLE
Modify Abstract and Preface

### PR DESCRIPTION
**Pull request by nob140**
I would like to propose several modifications of the Abstract part.

Basically, the modified points are same as for the Press Release in September.
1. Full implementation of the CM
2. Model driven approach, schemas are derived from UML model automatically
3. Compliant with ISO GML
4. GML version: 3.2.1 to 3.2. (proposed by Tatjana)

Other modifications are also included.
1. Modify "CityGML 3.0 GML encoding standard" to official specification name "CityGML 3.0 Part 2: GML Encoding Standard"
2. Add "(OGC 20-010)" linked to the internal reference. Is direct link (https://docs.ogc.org/is/20-010/20-010.html) better?
3. Modify "defined by" -> "specified by" to avoid duplicated sentences.

BTW, I didn't inlucde all sentences of the Press Release and modifiy the Preface part so much.
If these are sentences that should be included, please add them or let's discuss at the GML Encoding Sugroup meeting!
Thanks!

### CODE REVIEW

**Comment by 3DXScape** [comment]
Can we have an Encoding Subgroup meeting on the 17th to go over this and other recent updates?

**Comment by 3DXScape** [comment]
16:00 CET?

**Comment by nob140** [comment]
Hi Steve,It is OK for me!But since it is after midnight, I am happy if it will finish within one hour, or allow me to leave after one hour…Best regards,Nobu2022/11/08 20:51、Steve Smyth ***@***.***>のメール:﻿
16:00 CET?

**Comment by TatjanaKutzner** [comment]
Would be OK for me as well.

**Pull request merged**
